services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adilkadivala560
      - MONGO_INITDB_ROOT_PASSWORD=adilkadivala560
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=adilkadivala560
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adilkadivala560
      - ME_CONFIG_MONGODB_URL=mongodb://adilkadivala560:adilkadivala560@mongodb:27017/
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=secret
    depends_on:
      - mongodb

volumes:
  mongo_data:
